language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: saNJouiMH8m7MHlJCODXOS02GmGgkrrUlaqOwElscZC/Yh7RblUDd/esDUXV3whGhg02iHZmZcfJKXB3ia6lmb3Jp0UnzFworYUrsSJdDZ1RRNw2yWPZqd/qPrBSGq2S7QPnW2rWu9uMuQiLOj1Ya9SdiFPaKSQXWKXTTYcHPWVgfppAYDIUXt9LgUph/ZpA628yF6XcalPDHhez1kAECTyCj9al514Fcw8ENutMWcJZtLz1RneKWww3/vkhyzSZAUWO9bMJK4E2QqPGkZiXcV64I5DGzUukWmJVI5mpqI39doK9GP+deiG6N/NKp+9zHsu90GtuQ9HLHlbvMxJnA6aB7Q50avvlHVuOPVUvZKSQa1FLpzE14i/GcCShF8TGe2kzjySvtthKVA6r912S2G+LLwEPiD6L0lk9QebFIZQUncyeWbRpclAk2rYRyIUHvMThJISoj6lDnlVHbuUvYCj2hs6SK9th2OtPjs/FB7o8z6Oii5AvRXyxCU6y/jargCpYpQtb5oQ5Dehrvjyau4NZ8hdgM6XjX9xD3bk0R3b8V+GxF+9C3/NVJ11dEIMqacN0RA69cdHwUOWKwCZ4ZjZJw/kbfJvWVm9ujSjNdmLfdfWWTl3Cvs9xzpa1/5XBIVR1GkUQ93UXUOytzwkJLWEbre+8tegiCIX1F/9UuQg=
app: career-day-fe